name: auto pull
on: [push]
jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
    - name: ssh test
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USERNAME}}
        key: ${{secrets.KEY}}
        port: ${{secrets.PORT}}
        script: |
          cd CICD
          git pull

