name: auto pull
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0
      - name: Run Test
        run: |
          pip install -r requirements.txt
          pytest test.py

  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
    - name: ssh test
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USERNAME}}
        key: ${{secrets.KEY}}
        port: ${{secrets.PORT}}
        script: |
          cd CICD
          git pull
          docker rmi myimage
          docker stop mycontainer
          docker rm mycontainer
          docker build -t myimage .
          docker run --rm -d -it --name mycontainer -p 9000:9000 myimage


